version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile
    environment:
      DB_HOST: db # Nombre del servicio del contenedor MySQL
      DB_USER: root
      DB_PASSWORD: Gmatias1234!
      DB_DATABASE: stechsChallenge
      DB_CONNECTION_LIMIT: 10
    ports:
      - "3001:3001" # Exponer el puerto 3001 del backend

  db:
    image: mysql:5.7.34
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Gmatias1234!
      MYSQL_DATABASE: stechsChallenge
    volumes:
      - ./data/modems.sql:/docker-entrypoint-initdb.d/modems.sql
  phpmyadmin:
    container_name: db_admin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Gmatias1234! # O la contraseña que hayas configurado
